[project]
name = "neural-networks-from-scratch"
version = "0.1.0"
description = "Neural Networks from Scratch Scratchpad"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "matplotlib>=3.10.8",
    "numpy>=2.4.0",
]
